// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Zafch7_t5UpLIRoosncN8a8EX8BndKc',
    appId: '1:959547635123:web:eabac85a7ec48c1ba307c6',
    messagingSenderId: '959547635123',
    projectId: 'unplug-1da00',
    authDomain: 'unplug-1da00.firebaseapp.com',
    storageBucket: 'unplug-1da00.firebasestorage.app',
    measurementId: 'G-Q24CVQC7G1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr57HNmjc5XxdzoAZYtNddSu5HiW37Tsc',
    appId: '1:959547635123:android:42a444ad00576741a307c6',
    messagingSenderId: '959547635123',
    projectId: 'unplug-1da00',
    storageBucket: 'unplug-1da00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9eowS6-Q66vqtYhr3aOMYqjlssIpuqnA',
    appId: '1:959547635123:ios:6425e936d409a189a307c6',
    messagingSenderId: '959547635123',
    projectId: 'unplug-1da00',
    storageBucket: 'unplug-1da00.firebasestorage.app',
    androidClientId: '959547635123-duvr6o4nvkcclpkkcipfuc1ksiqbienh.apps.googleusercontent.com',
    iosClientId: '959547635123-18klk4v4djmoi0cas83i2a535bhauec0.apps.googleusercontent.com',
    iosBundleId: 'com.example.maeAssignmentFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9eowS6-Q66vqtYhr3aOMYqjlssIpuqnA',
    appId: '1:959547635123:ios:6425e936d409a189a307c6',
    messagingSenderId: '959547635123',
    projectId: 'unplug-1da00',
    storageBucket: 'unplug-1da00.firebasestorage.app',
    androidClientId: '959547635123-duvr6o4nvkcclpkkcipfuc1ksiqbienh.apps.googleusercontent.com',
    iosClientId: '959547635123-18klk4v4djmoi0cas83i2a535bhauec0.apps.googleusercontent.com',
    iosBundleId: 'com.example.maeAssignmentFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_Zafch7_t5UpLIRoosncN8a8EX8BndKc',
    appId: '1:959547635123:web:267c4112c3f392f9a307c6',
    messagingSenderId: '959547635123',
    projectId: 'unplug-1da00',
    authDomain: 'unplug-1da00.firebaseapp.com',
    storageBucket: 'unplug-1da00.firebasestorage.app',
    measurementId: 'G-RZK794W2XW',
  );

}