// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMevWGocaFZMEJAzSi7TqhloK0C8SNlmE',
    appId: '1:291012477513:web:58dfcb9792bec201a33598',
    messagingSenderId: '291012477513',
    projectId: 'firstproject-a1c4e',
    authDomain: 'firstproject-a1c4e.firebaseapp.com',
    storageBucket: 'firstproject-a1c4e.firebasestorage.app',
    measurementId: 'G-QNBNN1SR9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx9RrmeKREW86D8D0UhKpSkw9BfuZyn-o',
    appId: '1:291012477513:android:0bc631d5a3c5f203a33598',
    messagingSenderId: '291012477513',
    projectId: 'firstproject-a1c4e',
    storageBucket: 'firstproject-a1c4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5rrzMgL1X6KviRyTU0DNUz1Dm4Th-i8I',
    appId: '1:291012477513:ios:f59f942892c04967a33598',
    messagingSenderId: '291012477513',
    projectId: 'firstproject-a1c4e',
    storageBucket: 'firstproject-a1c4e.firebasestorage.app',
    iosBundleId: 'com.example.maeAssignmentFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5rrzMgL1X6KviRyTU0DNUz1Dm4Th-i8I',
    appId: '1:291012477513:ios:f59f942892c04967a33598',
    messagingSenderId: '291012477513',
    projectId: 'firstproject-a1c4e',
    storageBucket: 'firstproject-a1c4e.firebasestorage.app',
    iosBundleId: 'com.example.maeAssignmentFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMevWGocaFZMEJAzSi7TqhloK0C8SNlmE',
    appId: '1:291012477513:web:d9a7e046f0d0110aa33598',
    messagingSenderId: '291012477513',
    projectId: 'firstproject-a1c4e',
    authDomain: 'firstproject-a1c4e.firebaseapp.com',
    storageBucket: 'firstproject-a1c4e.firebasestorage.app',
    measurementId: 'G-4QW2QV2NLH',
  );
}
