// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMevWGocaFZMEJAzSi7TqhloK0C8SNlmE',
    appId: '1:291012477513:web:58dfcb9792bec201a33598',
    messagingSenderId: '291012477513',
    projectId: 'firstproject-a1c4e',
    authDomain: 'firstproject-a1c4e.firebaseapp.com',
    storageBucket: 'firstproject-a1c4e.firebasestorage.app',
    measurementId: 'G-QNBNN1SR9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx9RrmeKREW86D8D0UhKpSkw9BfuZyn-o',
    appId: '1:291012477513:android:0bc631d5a3c5f203a33598',
    messagingSenderId: '291012477513',
    projectId: 'firstproject-a1c4e',
    storageBucket: 'firstproject-a1c4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Zafch7_t5UpLIRoosncN8a8EX8BndKc',
    appId: '1:959547635123:web:eabac85a7ec48c1ba307c6',
    messagingSenderId: '959547635123',
    projectId: 'unplug-1da00',
    authDomain: 'unplug-1da00.firebaseapp.com',
    storageBucket: 'unplug-1da00.firebasestorage.app',
    measurementId: 'G-Q24CVQC7G1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9eowS6-Q66vqtYhr3aOMYqjlssIpuqnA',
    appId: '1:959547635123:ios:6425e936d409a189a307c6',
    messagingSenderId: '959547635123',
    projectId: 'unplug-1da00',
    storageBucket: 'unplug-1da00.firebasestorage.app',
    iosBundleId: 'com.example.maeAssignmentFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_Zafch7_t5UpLIRoosncN8a8EX8BndKc',
    appId: '1:959547635123:web:267c4112c3f392f9a307c6',
    messagingSenderId: '959547635123',
    projectId: 'unplug-1da00',
    authDomain: 'unplug-1da00.firebaseapp.com',
    storageBucket: 'unplug-1da00.firebasestorage.app',
    measurementId: 'G-RZK794W2XW',
  );
}
